-- BUSINESS QUESTIONS --

-- What is total revenue generated by male vs female customers?
select gender, sum(Purchase_Amount) as total_revenue
from customer_table
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount
select Customer_id, Purchase_Amount
from customer_table
where Discount_Applied = "Yes" and Purchase_Amount >= (
	select avg(Purchase_Amount)
    from customer_table
);

-- Which are the top 5 products with the highest average review rating?
 select Item_Purchased, round(avg(Review_Rating), 2) as average_review_rating
 from customer_table
 group by Item_Purchased
 order by average_review_rating desc
 limit 5;	
 
-- Campare the average purchase amount between standard and Express shipping 
select Shipping_Type, round(avg(Purchase_Amount),2) as Avg_Purchase_Amount
from customer_table
where Shipping_Type in ("Standard", "Express")
group by Shipping_Type;

-- Do subscribed customers spend more? Campare average spent and 
-- total revenue generated between subscribed and non subscribed customers
select Subscription_Status, 
count(Customer_id) as total_cust,
round(avg(Purchase_Amount), 2) as avg_spent,
round(sum(Purchase_Amount), 2) as total_revenue
from customer_table
group by Subscription_Status
order by avg_spent,total_revenue desc;

-- Which 5 products have the highest percentage of purchases with discounts applied ?
select Item_Purchased, 
ROUND(100 * sum(case when Discount_Applied = "Yes" then 1 else 0 END)/count(*), 2) AS Discount_rate
from customer_table
group by Item_Purchased
order by Discount_rate desc
limit 5;

-- Segment customers into New, Returning and Loyal based on their 
-- total no of previous purchases and show the count of each segment
with customer_type as (
	select Customer_id, Previous_Purchases,
    case 
		when Previous_Purchases = 1 THEN "New"
        when Previous_Purchases between 2 AND 10 then "Returning"
        else "Loyal"
	end as customer_segment
    from customer_table
)

select customer_segment, count(*) as total
from customer_type
group by customer_segment;

-- What are the top 3 most purchased products within each category
with items_count as (
	select Category, 
	Item_Purchased, 
	count(Customer_id) as total_purchase,
	row_number() over(partition by Category order by count(Customer_id) desc) as ranking
	from customer_table
	group by Category, Item_Purchased
) 
select ranking, Category, Item_Purchased, total_purchase
from items_count
where ranking <= 3;

-- Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe?
select Subscription_Status, count(Customer_id) as repeat_buyers
from customer_table
where Previous_Purchases > 5
group by Subscription_Status;

-- What is the revenue contribution of each age group
select Age_group, sum(Purchase_Amount) as total_revenue
from customer_table
group by Age_group
order by total_revenue desc;





